### PR TITLE
Working Server

### PR DESCRIPTION
**Pull request by big-nacho**

### CODE REVIEW

**Review by claas-c — CHANGES_REQUESTED** [review]
i would put the .py scripts into a src folder
also it would be good to add more comments, that explain every choice that was made. Ideally write comments for someone who has no idea how this works
or are there some docs already in notion?

**Comment by big-nacho** [comment]
Added some comments to the code. I will add a Notion document as well. Also, I need to take a look into image reading from url. Query parameters seem to not be affecting anything. Not sure if it's relevant for our use case but it would be nice to have it working.

**Comment by explodi** [comment]
> Added some comments to the code. I will add a Notion document as well. Also, I need to take a look into image reading from url. Query parameters seem to not be affecting anything. Not sure if it's relevant for our use case but it would be nice to have it working.

Maybe it's easier to handle query parameters in URLs when the endpoint is POST instead of GET

**Comment by big-nacho** [comment]
I've added a short [Notion Article](https://www.notion.so/kittl/Image-Tracing-ffe0dc8dfafa4d66ad533f9d6b98f6ed) with some general pointers

**Review by claas-c — APPROVED** [review]
lgtm

**Comment by big-nacho** [comment]
@claas-c @explodi I've re-arranged the code a bit. Would be nice to get a quick look on that. Also, it should be noted that now the endpoint expects a POST request with form data. This way query params are handled nicely.

**Pull request merged**
